package com.guesschess.domain.game;

public enum GameResultCause {
    CHECKMATE,
    KING_CAPTURED,
    CHECK_PARRY_GUESSED,
    STALEMATE,
    DRAW_FIFTY_MOVE_RULE,
    DRAW_THREEFOLD_REPETITION,
    DRAW_THREE_GUESS_REPETITION,
    DRAW_INSUFFICIENT_MATERIAL,
    DRAW_BY_AGREEMENT,
    TIMEOUT
}
